export const ErrorCode = {
  HTTP_ERROR: 'HTTP_ERROR',
  // Auth
  UNAUTHORIZED: 'UNAUTHORIZED',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_TOKEN_EXPIRED: 'AUTH_TOKEN_EXPIRED',
  AUTH_FORBIDDEN: 'AUTH_FORBIDDEN',
  EMAIL_ALREADY_EXISTED: 'EMAIL_ALREADY_EXISTED',

  USER_NOT_FOUND: 'USER_NOT_FOUND',
  UNKNOWN: 'UNKNOWN',
  VALIDATION: 'VALIDATION',

  // Settings
  SETTING_NOT_FOUND: 'SETTING_NOT_FOUND',

  //OTP
  OTP_COOLDOWN_ACTIVE: 'OTP_COOLDOWN_ACTIVE',
  OTP_TOO_MANY_REQUEST: 'OTP_TOO_MANY_REQUEST',
  OTP_NOT_WORKING: 'OTP_NOT_WORKING',
  OTP_TOO_MANY_ATTEMPTS: 'OTP_TOO_MANY_ATTEMPTS',
  OTP_EXPIRED: 'OTP_EXPIRED',

  //Upload
  FILE_IS_REQUIRED: 'FILE_IS_REQUIRED',
  INVALID_FILE_TYPE: 'INVALID_FILE_TYPE',
  FILE_TOO_LARGE: 'FILE_TOO_LARGE',
  FILE_UNKNOWN: 'FILE_UNKNOWN',
  UPLOAD_WORKING: 'UPLOAD_WORKING',

  //Taxonomy
  CATEGORY_WORKING: 'CATEGORY_WORKING',

  //Post
  POST_NOT_FOUND: 'POST_NOT_FOUND',

  //Comment Reaction
  TOGGLE_REACTION_COMMENT_WORKING: 'TOGGLE_REACTION_COMMENT_WORKING',
  CREATE_COMMENT_WORKING: 'CREATE_COMMENT_WORKING',
  COMMENT_NOT_FOUND: 'COMMENT_NOT_FOUND',
} as const;

export type ErrorCodeType = (typeof ErrorCode)[keyof typeof ErrorCode];
